### PR TITLE
Verify manifests script

### LINKED ISSUE #73: CI should fail if CRD manifests are out of date
/kind bug

**What steps did you take and what happened:**
1. Modify a field in a CRD, such as changing the json tag
1. Run `hack/verify-all.sh`
1. It passes

**What did you expect to happen:**
1. It should fail because the generated manifests are out of date

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster API version:
- Cluster API Bootstrap Provider Kubeadm version:
- Cluster API Infrastructure Provider version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by amy**
**What this PR does / why we need it**:
- Adds verify manifests script

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #73

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -53,8 +59,8 @@ deploy: manifests
 
 # Generate manifests e.g. CRD, RBAC etc.
 .PHONY: manifests
-manifests: $(CONTROLLER_GEN)
-	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
+manifests: controller-gen
```
Comment (ncdc) [inline Makefile]: Revert please and I'm guessing some of the other diffs in the PR might end up getting undone as well (different controller-gen version).

File: hack/verify-manifests.sh [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    rm -rf "${TMP_ROOT}"
+}
+trap "cleanup" EXIT SIGINT
+cleanup
+
+MANIFEST_ROOT=$TMP_ROOT make manifests
+
+echo "diffing ${DIFFROOT} against freshly generated manifests"
+ret=0
+git diff --no-index --diff-filter=MD ${TMP_ROOT} ${DIFFROOT} > /dev/null 2>&1 || ret=$?
```
Comment (amy) [inline hack/verify-manifests.sh]: I am using `git diff` rather than `diff` here because the output is cleaner. I can't get `diff` to ignore files not present in the `TMP_ROOT`. There are many files in `DIFFROOT` that don't seem to be generated files.

Comment (ncdc) [reply hack/verify-manifests.sh]: `git diff` will not see newly created files, so this test won't be 100% sufficient

Comment (amy) [reply hack/verify-manifests.sh]: This test...
- generates expected manifest files in `_tmp`
- `git diff` will...
  - see if `/config` has all the files generated in `_tmp`
  - diff the matching `/config` and `_tmp` files

In which situation do we need to see newly created files in `config`.

Comment (amy) [reply hack/verify-manifests.sh]: This test will...
- run `make manifests` and output the results into `_tmp`
- `git diff` will...
  - see if there exists files in `_tmp` that don't exist in `config`
  - see if the matching files in `_tmp` and `config` are the same

If by "newly created files" you mean files that exist in `config` and not in `_tmp`, there seemed to be many files in `config` that weren't generated.

Can you elaborate.

Comment (ncdc) [reply hack/verify-manifests.sh]: Nevermind, I didn't see this was using `--no-index`. My bad!

Comment (amy) [reply hack/verify-manifests.sh]: dope. Thanks for reviewing!

Comment (ncdc) [inline hack/verify-manifests.sh]: Instead of redirecting to `/dev/null`, could you use the `--stat` flag to at least print a list of the files that it thinks are out of date?

Comment (amy) [reply hack/verify-manifests.sh]: sure

**Comment by ncdc** [comment]
@amy now that you have the file diff 😄:
```
diffing hack/../config against freshly generated manifests
 .../bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml | 26 ++++++++++++++++++++++
 1 file changed, 26 insertions(+)
Manifests in hack/../config are out of date. Please run `make manifests`
```

Can you see if something truly is out of date?

**Comment by amy** [comment]
Yah. Just did another rebase. Looks like running `make manifests` again removes this:
```
-            additionalUserDataFiles:
-              description: AdditionalUserDataFiles specifies extra files to be passed
-                to user_data upon creation.
-              items:
-                description: Files defines the input for generating write_files in
-                  cloud-init.
-                properties:
-                  content:
-                    description: Content is the actual content of the file.
-                    type: string
-                  owner:
-                    description: Owner specifies the ownership of the file, e.g. "root:root".
-                    type: string
-                  path:
-                    description: Path specifies the full path on disk where to store
-                      the file.
-                    type: string
-                  permissions:
-                    description: Permissions specifies the permissions to assign to
-                      the file, e.g. "0640".
-                    type: string
-                required:
-                - content
-                - path
-                type: object
-              type: array
```

**Comment by ncdc** [comment]
ugh, apparently yesterday's rebase of #42 managed to eliminate part/all of #57 😦 cc @chuckha

**Comment by ncdc** [comment]
I've fixed master so now we shouldn't fail manifest verification (#89)

**Comment by chuckha** [comment]
oh nooo, did i hose a rebase -_-
